services:
  backend:
    image: ghcr.io/raycronin/packaging-professionals-capstone-backend:latest
    ports:
      - "5000:5000"

  frontend:
    image: ghcr.io/raycronin/packaging-professionals-capstone-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
# Need to map volumes for persistent data storage for the backend
    volumes:
      - backend-data:/docker/IMS