services:
  backend:
    build:
      context: ./back-end
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - backend-data:/app/data #docker managed volume for DB
      - /home/serveruser/capstone/orders:/app/orders #host directory for order summaries
      - /home/serveruser/capstone/count:/app/counts #host directory for count sheets
    networks:
      - app-network

  frontend:
    build:
      context: ./front-end
    container_name: frontend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - app-network
        
networks:
  app-network:
    driver: bridge
    
volumes:
  backend-data:

