services:
  backend:
    image: raycronin/packaging-professionals-capstone-backend:latest
    expose:
      - "5000"
    volumes:
      - backend-data:/app/data
      - /Order-Summaries:/app/orders
      - /Count-Sheets:/app/counts
    networks:
      - app-network

  frontend:
    image: raycronin/packaging-professionals-capstone-frontend:latest
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend-data:
